version: '3.7'
services:
# ==============================================================================
  web:
    image: verbral/php-theia:7.4
    working_dir: /home/project
    environment:
      APACHE_DOCUMENT_ROOT: /home/project/web
      PHP_EXTENSION_BLACKFIRE: 1
      PHP_EXTENSION_GD: 1
      PHP_EXTENSION_BCMATH: 1
      PHP_INI_ERROR_REPORTING: E_ALL
      PHP_INI_MEMORY_LIMIT: 2g
      WAKATIME_API_KEY:
      GIT_USER_NAME:
      GIT_USER_EMAIL:
    volumes:
      - ${PWD}:/home/project
      - ~/.ssh:/home/docker/.ssh
      - ~/.composer:/home/docker/.composer
    ports:
      - 80
      - 3000
# ==============================================================================
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=drupal
    volumes:
      - mysql:/var/lib/mysql
# ==============================================================================
volumes:
  mysql:
